# **Penting**
- Jangan mengubah atau menambahkan cell text yang sudah disediakan, Anda hanya perlu mengerjakan cell code yang sudah disediakan.
- Pastikan seluruh kriteria memiliki output yang sesuai, karena jika tidak ada output dianggap tidak selesai.
- Misal, Anda menggunakan df = df.dropna() silakan gunakan df.isnull().sum() sebagai tanda sudah berhasil. Silakan sesuaikan seluruh output dengan perintah yang sudah disediakan.
- Pastikan Anda melakukan Run All sebelum mengirimkan submission untuk memastikan seluruh cell berjalan dengan baik.
- Pastikan Anda menggunakan variabel df dari awal sampai akhir dan tidak diperbolehkan mengganti nama variabel tersebut.
- Hapus simbol pagar (#) pada kode yang bertipe komentar jika Anda menerapkan kriteria tambahan
- Biarkan simbol pagar (#) jika Anda tidak menerapkan kriteria tambahan
- Pastikan Anda mengerjakan sesuai section yang sudah diberikan tanpa mengubah judul atau header yang disediakan.

# **1. Import Library**
Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning.

In [13]:
#Type your code here
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import joblib
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.model_selection import RandomizedSearchCV

# **2. Memuat Dataset dari Hasil Clustering**
Memuat dataset hasil clustering dari file CSV ke dalam variabel DataFrame.

In [14]:
# Gunakan dataset hasil clustering yang memiliki fitur Target
# Silakan gunakan dataset data_clustering jika tidak menerapkan Interpretasi Hasil Clustering [Advanced]
# Silakan gunakan dataset data_clustering_inverse jika menerapkan Interpretasi Hasil Clustering [Advanced]
# Lengkapi kode berikut
df = pd.read_csv("data_clustering_inverse.csv")

In [15]:
# Tampilkan 5 baris pertama dengan function head.
df.head()

TransactionAmount TransactionType   Location Channel  CustomerAge  \
0              14.09           Debit  San Diego     ATM         70.0   
1             376.24           Debit    Houston     ATM         68.0   
2             126.29           Debit       Mesa  Online         19.0   
3             184.50           Debit    Raleigh  Online         26.0   
4              13.45          Credit    Atlanta  Online         23.0   

  CustomerOccupation  TransactionDuration  LoginAttempts  AccountBalance  \
0             Doctor                 81.0            1.0         5112.21   
1             Doctor                141.0            1.0        13758.91   
2            Student                 56.0            1.0         1122.35   
3            Student                 25.0            1.0         8569.06   
4            Student                198.0            1.0         7429.40   

   TransactionSpan  Outlier_Attempts AgeGroup  Target  
0            572.0                 0      60+       1  
1            495.0                 0      60+       0  
2            482.0                 0    18-30       1  
3            548.0                 0    18-30       1  
4            384.0                 0    18-30       0

# **3. Data Splitting**
Tahap Data Splitting bertujuan untuk memisahkan dataset menjadi dua bagian: data latih (training set) dan data uji (test set).

In [16]:
# Menggunakan train_test_split() untuk melakukan pembagian dataset.
encoders = {}
categorical_columns = ['TransactionType', 'Location', 'Channel', 'CustomerOccupation', 'AgeGroup']
for column in categorical_columns:
    encoder = LabelEncoder()
    encoder.fit(df[column])
    df[column] = encoder.transform(df[column])
    encoders[column] = encoder
    
X = df.drop(columns=['Target'])
y = df['Target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# **4. Membangun Model Klasifikasi**
Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Menggunakan algoritma klasifikasi yaitu Decision Tree.
2. Latih model menggunakan data yang sudah dipisah.

In [17]:
# Buatlah model klasifikasi menggunakan Decision Tree
model_dt = DecisionTreeClassifier()
model_dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [18]:
# Menyimpan Model
# import joblib
joblib.dump(model_dt, 'decision_tree_model.h5')

['decision_tree_model.h5']

# **5. Memenuhi Kriteria Skilled dan Advanced dalam Membangun Model Klasifikasi**



**Biarkan kosong jika tidak menerapkan kriteria skilled atau advanced**

In [19]:
# Melatih model menggunakan algoritma klasifikasi scikit-learn selain Decision Tree.
model_svm = SVC()
model_svm.fit(X_train, y_train)
y_pred = model_svm.predict(X_test)

In [20]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada seluruh algoritma yang sudah dibuat.
def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    cm = confusion_matrix(y_test, y_pred)

    results = {
        'Confusion Matrix': cm,
        'Accuracy': accuracy_score(y_test, y_pred),
        'Precision': precision_score(y_test, y_pred, average='weighted'),
        'Recall': recall_score(y_test, y_pred, average='weighted'),
        'F1-Score': f1_score(y_test, y_pred, average='weighted')
    }
    return results

results = {
    'Decision Tree (DT)': evaluate_model(model_dt, X_test, y_test),
    'Support Vector Machine (SVM)': evaluate_model(model_svm, X_test, y_test),
}

for model_name, metrics in results.items():
    print(f"--- {model_name} ---")
    print(f"Confusion Matrix:\n{metrics['Confusion Matrix']}")
    print(f"Accuracy: {metrics['Accuracy']:.4f}")
    print(f"Precision: {metrics['Precision']:.4f}")
    print(f"Recall: {metrics['Recall']:.4f}")
    print(f"F1-Score: {metrics['F1-Score']:.4f}")
    print("-" * (len(model_name) + 6))

--- Decision Tree (DT) ---
Confusion Matrix:
[[178   0   3   5]
 [  0 168   0   4]
 [  0   0  66   0]
 [  6   0   0  68]]
Accuracy: 0.9639
Precision: 0.9647
Recall: 0.9639
F1-Score: 0.9641
------------------------
--- Support Vector Machine (SVM) ---
Confusion Matrix:
[[ 91  95   0   0]
 [ 60 111   0   1]
 [ 31  31   0   4]
 [ 15  21   0  38]]
Accuracy: 0.4819
Precision: 0.4524
Recall: 0.4819
F1-Score: 0.4523
----------------------------------


c:\Users\Khatama\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [21]:
# Menyimpan Model Selain Decision Tree
# Model ini bisa lebih dari satu
# import joblib
joblib.dump(model_svm, 'explore_svm_classification.h5')

['explore_svm_classification.h5']

Hyperparameter Tuning Model

Pilih salah satu algoritma yang ingin Anda tuning

In [22]:
# Lakukan Hyperparameter Tuning dan Latih ulang.
# Lakukan dalam satu cell ini saja.
random_search = RandomizedSearchCV(
    estimator=DecisionTreeClassifier(),
    param_distributions={
        'max_depth': [None, 10, 20, 30],
        'min_samples_split': [2, 5, 10],
        'min_samples_leaf': [1, 2, 4],
        'criterion': ['gini', 'entropy'],
        'splitter': ['best', 'random'],
    },
    n_iter=50,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    verbose=1,
    random_state=42
)
random_search.fit(X_train, y_train)
best_dt_model = DecisionTreeClassifier(**random_search.best_params_)
best_dt_model.fit(X_train, y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits


DecisionTreeClassifier(criterion='entropy', max_depth=10, min_samples_split=10)

In [23]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada algoritma yang sudah dituning.
results_tuned = {
    'Decision Tree (DT)': evaluate_model(best_dt_model, X_test, y_test),
}

for model_name, metrics in results_tuned.items():
    print(f"--- {model_name} ---")
    print(f"Confusion Matrix:\n{metrics['Confusion Matrix']}")
    print(f"Accuracy: {metrics['Accuracy']:.4f}")
    print(f"Precision: {metrics['Precision']:.4f}")
    print(f"Recall: {metrics['Recall']:.4f}")
    print(f"F1-Score: {metrics['F1-Score']:.4f}")
    print("-" * (len(model_name) + 6))

--- Decision Tree (DT) ---
Confusion Matrix:
[[177   0   4   5]
 [  0 172   0   0]
 [  0   0  66   0]
 [  2   4   0  68]]
Accuracy: 0.9699
Precision: 0.9702
Recall: 0.9699
F1-Score: 0.9698
------------------------


In [24]:
# Menyimpan Model hasil tuning
# import joblib
joblib.dump(best_dt_model, 'tuning_classification.h5')

['tuning_classification.h5']

End of Code